# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87249f861403c13fddb0ff1a94f14eb1cd560b5b5a2a82e4af20ea2f1e92651ec8046a15d1f1dfe9945dcab5cecb3dc9f817d29e8cd8a928355fa3ca46148913

test:
  secret_key_base: 36c5c228fdbcfa61623298b9172bc160dd31aeef59f8df34d65e835fb9d47ae52afebe81132fb8b349123e545bb9c72abf56f3aae3795ad677b163391b421950

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
